baseURL = "https://hugo-progression.com"
languageCode = "en-us"
title = "Dummy Co Ltd Progression Framework"
theme = "hugo-progression"
publishDir = "docs"

#googleAnalytics = "UI-XXXXX-XX"

[markup.goldmark.renderer]
unsafe= true

[menu]
[[menu.main]]
  identifier = "engineering"
  name       = "Engineering"
  url        = "/engineering"
[[menu.main]]
  identifier = "operations"
  name       = "Operations"
  url        = "/operations"
